import React, { ReactNode } from "react";
import Head from "next/head";
import { Footer } from "./Footer";
import { Navbar } from "./Navbar";

export const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Polygon Monkey Society</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="bg-[url('/background.png')] bg-center max-h-screen h-screen relative">
        <Navbar />
        <div className="container mx-auto px-10 h-screen">{children}</div>
        <Footer />
      </main>
    </>
  );
};
